<a href="https://colab.research.google.com/github/Lucas-Petrus/DS-Unit-1-Sprint-2-Statistics/blob/master/Lucas_Petrus_Updated_LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [2]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-06-09 20:26:07--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.1s    

2020-06-09 20:26:08 (153 KB/s) - ‘student.zip’ saved [20478/20478]



In [3]:
!unzip student.zip

Archive:  student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [4]:
from scipy import stats
import pandas as pd
import numpy as np

df = pd.read_csv('student-mat.csv', sep=';')

print(df.shape)
df.head()

(395, 33)


school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [10]:
df['goout'].value_counts().sort_index()

1     23
2    103
3    130
4     86
5     53
Name: goout, dtype: int64

In [11]:
df['freetime'].value_counts().sort_index()

1     19
2     64
3    157
4    115
5     40
Name: freetime, dtype: int64

In [12]:
contingency = pd.crosstab(df['goout'], df['freetime'])

contingency

freetime  1   2   3   4   5
goout                      
1         4   5   5   5   4
2         8  27  41  18   9
3         5  17  70  34   4
4         1  11  26  41   7
5         1   4  15  17  16

In [13]:
###FOR MY DEPENDENT CHOICE PAIR 1###

chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table", expected)

chi2 statistic 80.87785174188721
p value 1.155517403684047e-10
degrees of freedom 16
expected frequencies table [[ 1.10632911  3.72658228  9.14177215  6.69620253  2.32911392]
 [ 4.95443038 16.68860759 40.93924051 29.98734177 10.43037975]
 [ 6.25316456 21.06329114 51.67088608 37.84810127 13.16455696]
 [ 4.13670886 13.93417722 34.18227848 25.03797468  8.70886076]
 [ 2.54936709  8.58734177 21.06582278 15.43037975  5.36708861]]


In [38]:
df['Dalc'].value_counts().sort_index()

1    276
2     75
3     26
4      9
5      9
Name: Dalc, dtype: int64

In [39]:
df['Walc'].value_counts().sort_index()

1    151
2     85
3     80
4     51
5     28
Name: Walc, dtype: int64

In [40]:
contingency1b = pd.crosstab(df['Dalc'], df['Walc'])

contingency1b

Walc    1   2   3   4  5
Dalc                    
1     150  65  42  15  4
2       1  18  29  22  5
3       0   1   8  11  6
4       0   1   1   3  4
5       0   0   0   0  9

In [41]:
###SECOND DEPENDENT CHOICE#####

chi2, p_value, dof, expected = stats.chi2_contingency(contingency1b)

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table", expected)

chi2 statistic 287.0019095823893
p value 1.2457721336028707e-51
degrees of freedom 16
expected frequencies table [[105.50886076  59.39240506  55.89873418  35.63544304  19.56455696]
 [ 28.67088608  16.13924051  15.18987342   9.6835443    5.3164557 ]
 [  9.93924051   5.59493671   5.26582278   3.35696203   1.84303797]
 [  3.44050633   1.93670886   1.82278481   1.16202532   0.63797468]
 [  3.44050633   1.93670886   1.82278481   1.16202532   0.63797468]]


In [18]:
df['traveltime'].value_counts().sort_index()

1    257
2    107
3     23
4      8
Name: traveltime, dtype: int64

In [19]:
df['absences'].value_counts().sort_index()

0     115
1       3
2      65
3       8
4      53
5       5
6      31
7       7
8      22
9       3
10     17
11      3
12     12
13      3
14     12
15      3
16      7
17      1
18      5
19      1
20      4
21      1
22      3
23      1
24      1
25      1
26      1
28      1
30      1
38      1
40      1
54      1
56      1
75      1
Name: absences, dtype: int64

In [23]:
contingency2b = pd.crosstab(df['traveltime'], df['absences'])

contingency2b

absences    0   1   2   3   4   5   6   7   ...  26  28  30  38  40  54  56  75
traveltime                                  ...                                
1           74   2  40   5  37   4  16   5  ...   0   1   0   0   1   1   1   0
2           32   1  20   2  13   1  10   1  ...   1   0   1   1   0   0   0   1
3            6   0   4   1   3   0   3   1  ...   0   0   0   0   0   0   0   0
4            3   0   1   0   0   0   2   0  ...   0   0   0   0   0   0   0   0

[4 rows x 34 columns]

In [31]:
###FOR MY 1ST INDEPENDENT CHOICE

chi2, p_value, dof, expected = stats.chi2_contingency(contingency2b)

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table", expected)

chi2 statistic 61.11558335253091
p value 0.9990069240658936
degrees of freedom 99
expected frequencies table [[7.48227848e+01 1.95189873e+00 4.22911392e+01 5.20506329e+00
  3.44835443e+01 3.25316456e+00 2.01696203e+01 4.55443038e+00
  1.43139241e+01 1.95189873e+00 1.10607595e+01 1.95189873e+00
  7.80759494e+00 1.95189873e+00 7.80759494e+00 1.95189873e+00
  4.55443038e+00 6.50632911e-01 3.25316456e+00 6.50632911e-01
  2.60253165e+00 6.50632911e-01 1.95189873e+00 6.50632911e-01
  6.50632911e-01 6.50632911e-01 6.50632911e-01 6.50632911e-01
  6.50632911e-01 6.50632911e-01 6.50632911e-01 6.50632911e-01
  6.50632911e-01 6.50632911e-01]
 [3.11518987e+01 8.12658228e-01 1.76075949e+01 2.16708861e+00
  1.43569620e+01 1.35443038e+00 8.39746835e+00 1.89620253e+00
  5.95949367e+00 8.12658228e-01 4.60506329e+00 8.12658228e-01
  3.25063291e+00 8.12658228e-01 3.25063291e+00 8.12658228e-01
  1.89620253e+00 2.70886076e-01 1.35443038e+00 2.70886076e-01
  1.08354430e+00 2.70886076e-01 8.12658228e-01 2.708

In [14]:
df['health'].value_counts().sort_index()

1     47
2     45
3     91
4     66
5    146
Name: health, dtype: int64

In [15]:
df['famrel'].value_counts().sort_index()

1      8
2     18
3     68
4    195
5    106
Name: famrel, dtype: int64

In [16]:
contingency2 = pd.crosstab(df['health'], df['famrel'])

contingency2

famrel  1  2   3   4   5
health                  
1       4  2   7  19  15
2       0  3   9  22  11
3       1  5  22  45  18
4       0  4  11  32  19
5       3  4  19  77  43

In [17]:
###FOR MY 2nd INDEPENDENT CHOICE####

chi2, p_value, dof, expected = stats.chi2_contingency(contingency2)

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table", expected)

chi2 statistic 22.636402802674013
p value 0.12380538843085523
degrees of freedom 16
expected frequencies table [[ 0.95189873  2.14177215  8.09113924 23.20253165 12.61265823]
 [ 0.91139241  2.05063291  7.74683544 22.21518987 12.07594937]
 [ 1.84303797  4.14683544 15.66582278 44.92405063 24.42025316]
 [ 1.33670886  3.00759494 11.36202532 32.58227848 17.71139241]
 [ 2.95696203  6.65316456 25.13417722 72.07594937 39.17974684]]


### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [42]:
df['health'].value_counts()

5    146
3     91
4     66
1     47
2     45
Name: health, dtype: int64

In [43]:
df['famrel'].value_counts()

4    195
5    106
3     68
2     18
1      8
Name: famrel, dtype: int64

In [47]:
observed = pd.crosstab(df['health'], df['famrel'])

observed

famrel  1  2   3   4   5
health                  
1       4  2   7  19  15
2       0  3   9  22  11
3       1  5  22  45  18
4       0  4  11  32  19
5       3  4  19  77  43

In [45]:
observed_with_margins = pd.crosstab(df['health'], df['famrel'], margins=True)

observed_with_margins

famrel  1   2   3    4    5  All
health                          
1       4   2   7   19   15   47
2       0   3   9   22   11   45
3       1   5  22   45   18   91
4       0   4  11   32   19   66
5       3   4  19   77   43  146
All     8  18  68  195  106  395

In [48]:
observed = observed.values
observed

array([[ 4,  2,  7, 19, 15],
       [ 0,  3,  9, 22, 11],
       [ 1,  5, 22, 45, 18],
       [ 0,  4, 11, 32, 19],
       [ 3,  4, 19, 77, 43]])

In [49]:
row_totals = df['famrel'].value_counts().sort_index().values

row_totals

array([  8,  18,  68, 195, 106])

In [50]:
col_totals = df['health'].value_counts().sort_index().values

col_totals

array([ 47,  45,  91,  66, 146])

In [51]:
sample_size = df.shape[0]

sample_size

395

In [56]:

for i, col in enumerate(col_totals):
  for j, row in enumerate(row_totals): 
    expected_value = (row*col / sample_size)
    print(expected_value, i, j)


0.9518987341772152 0 0
2.141772151898734 0 1
8.09113924050633 0 2
23.20253164556962 0 3
12.612658227848101 0 4
0.9113924050632911 1 0
2.050632911392405 1 1
7.746835443037975 1 2
22.21518987341772 1 3
12.075949367088608 1 4
1.8430379746835444 2 0
4.146835443037975 2 1
15.665822784810127 2 2
44.924050632911396 2 3
24.42025316455696 2 4
1.3367088607594937 3 0
3.007594936708861 3 1
11.362025316455696 3 2
32.58227848101266 3 3
17.71139240506329 3 4
2.956962025316456 4 0
6.653164556962025 4 1
25.134177215189872 4 2
72.07594936708861 4 3
39.17974683544304 4 4


## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [0]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?
it is the of a value of a descripitive characteristic of a sampling distribution

- What are hypothesis test? How are they useful?
A hypothesis test takes two mutually exclusive statements about a population to determine which statement best describes the population. They are useful because they allow you to see with a smaller portion of data and see if something correlates (correlation doesnt equal causation though) and helps us to spot trends

- What is a "null hypothesis?"
a null hypothesis states that there is no significant difference between specified populations and if there is that it must be atributed to error or misrepresentation

- What is a p-value and what does it represent?
the pvalue is a measurement of how much evidence we have against a null hypothesis. it is important because it demonstrates statistically why there is (or is not) a difference in numbers 

- What does it mean for something to be "statistically significant?"


- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

In [0]:
- What is a sample "estimate" in statistics?
it is the of a value of a descripitive characteristic of a sampling distribution

- What are hypothesis test? How are they useful?
A hypothesis test takes two mutually exclusive statements about a population to determine which statement best describes the population. 
They are useful because they allow you to see with a smaller portion of data and see if something correlates 
(correlation doesnt equal causation though) and helps us to spot trends

- What is a "null hypothesis?"
a null hypothesis states that there is no significant difference between specified populations 
and if there is that it must be atributed to error or misrepresentation

- What is a p-value and what does it represent?
the pvalue is a measurement of how much evidence we have against a null hypothesis. 
it is important because it demonstrates statistically why there is (or is not) a difference in numbers 

- What does it mean for something to be "statistically significant?"
it means that the result is unlikely due to chance

-What is a test statistic and how does it relate to a p-value?
A test statistic is used in a hypothesis test when you are deciding to support or reject the null hypothesis. 
The test statistic takes your data from an experiment or survey and compares your results to the results you would expect from the null hypothesis.
it relates to the pvalue because the pvalue gives it a confidence interval to tell you if the results you obtained were more likely chance or not by chance

What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?
degrees of freedom are the number of independent quantinties that can be assigned to a statisical distribitution
in 1 sample they are calucated by n-1
in 2 sample they are calculated by (n1+n2)-2

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)